
const skillsByDomain = {
    Informatique: [
      "Java", 
      "Python", 
      "JavaScript", 
      "C++", 
      "Ruby", 
      "Go", 
        "Swift",
        "Kotlin",
        "C#",
        "Scala",
        "R",
        "Perl",
        "Matlab",
        "Objective-C",
        "TypeScript",
        "Flutter",
        "Dart",
        "Ruby on Rails",
        "Laravel",
        "Symfony",
        "CodeIgniter",
        "CakePHP",
        "Zend",
        "Yii",
        "ASP.NET",
      "PHP", 
      "HTML", 
      "CSS", 
      "SQL",
        "React",
        "Angular",
        "Node.js",
        "MongoDB",
        "Express.js",
        "Django",
        "Flask",
        "Spring",
        "Hibernate",
        "JPA",
        "JSP",
        "Servlet",
        "JDBC",
        "ASP.NET MVC",
        "Entity Framework",
        "LINQ",
        "WPF",
        "SPA",
        "AJAX",
        "jQuery",
        "Bootstrap",
        


    ],
    Finance: [
      "Accounting", 
      "Financial Analysis", 
      "Excel", 
      "SAP", 
      "QuickBooks", 
      "Tax Preparation", 
      "Auditing", 
      "Budgeting",
        "Financial Reporting",
        "Financial Planning",
        "Financial Modeling",
        "Business Analysis",
        "Risk Management",
        "Investment Management",
        "Portfolio Management",
        "Financial Markets",
        "Banking",
    ],
    Mecanique: [
      "AutoCAD", 
      "SolidWorks", 
      "Mechanical Design", 
      "Fluid Mechanics", 
      "Thermodynamics", 
      "Machine Design", 
      "Manufacturing Processes",
        "CAD",
        "CAM",
        "CAE",
        "CFD",
        "FEM",
        "ANSYS",
        "CATIA",
        "Pro/ENGINEER",
        "NX",
        "Solid Edge",
        "HyperMesh",
        "ABAQUS",
        "Hypermesh",
        "Nastran",
        "Patran",
        "LS-DYNA",
        "COMSOL",
        "OpenFOAM",
        "Fluent",
        "Star-CCM+",
        "AutoForm",
        "PAM-CRASH",
        "PAM-STAMP",
        "Moldflow",
        "Moldex3D",
        "Cimatron",
        "Mastercam",
        "EdgeCAM",
        "PowerMill",
        "GibbsCAM",
        "Esprit",
        "SolidCAM",
        "FeatureCAM",
        "CAMWorks",
        "TopSolid",
        "WorkNC",
        "SurfCAM",
        "VisualCAM",
        "ArtCAM",
        "BobCAD-CAM",
        "OneCNC",
        "ZW3D",
        "DraftSight",
        "TurboCAD",
        "BricsCAD",
        "CMS IntelliCAD",
        "ProgeCAD",
        "ZWCAD",
        "nanoCAD",
        "DraftSight",
        "LibreCAD",
        "BRL-CAD",
        "OpenSCAD",
        "SolveSpace",
        "DesignSpark Mechanical",
        "KiCAD",
        "EAGLE",
        "Fritzing",
        "gEDA",
        "OrCAD",
        "Altium Designer",
        "PADS",
        "KiCAD",
        "EAGLE",
        "Fritzing",
        "gEDA",
        "OrCAD",
        "Altium Designer",
        "PADS",
        "KiCAD",
        "EAGLE",
        "Fritzing",
        "gEDA",
        "OrCAD",
        "Altium Designer",
        "PADS",
        "KiCAD",
        "EAGLE",
        "Fritzing",
        "gEDA",
        "OrCAD",
        "Altium Designer",
        "PADS",
        "KiCAD",
        "EAGLE",
        "Fritzing",
        "gEDA",
        "OrCAD",
        "Altium Designer",

    ],
    Marketing: [
      "3D Modeling", 
      "Figma", 
      "Adobe Photoshop", 
      "SEO", 
      "Content Creation", 
      "Digital Marketing", 
      "Social Media Management", 
      "Market Research",
        "Marketing Strategy",
        "Marketing Communications",
        "Brand Management",
        "Public Relations",
        "Advertising",
        "Event Planning",
        "Email Marketing",
        "Social Media Marketing",
        "Content Marketing",
        "Influencer Marketing",
        "Affiliate Marketing",
        "Search Engine Marketing",
        "Search Engine Optimization",
        "Pay-Per-Click Advertising",
        "Google Ads",
        "Facebook Ads",
        "Instagram Ads",
        "LinkedIn Ads",
        "Twitter Ads",
        "Pinterest Ads",
        "Snapchat Ads",
        "TikTok Ads",
        "YouTube Ads",
        "Google Analytics",
        "Google Tag Manager",
        "Google Search Console",
        "Google Data Studio",
        "Facebook Analytics",
        "Instagram Analytics",
        "LinkedIn Analytics",
        "Twitter Analytics",
        "Pinterest Analytics",
        "Snapchat Analytics",
        "TikTok Analytics",
        "YouTube Analytics",
        "Mailchimp",
        "HubSpot",
        "Marketo",
        "Pardot",
        "Salesforce",
        "Zoho CRM",
        "Microsoft Dynamics CRM",
        "SAP CRM",
        "Oracle CRM",
        "SugarCRM",
        "Vtiger CRM",
        "Insightly",
        "Nimble",
        "Copper",
        "Freshsales",
        "Zendesk Sell",
        "Pipedrive",
        "HubSpot CRM",
        "Salesforce Sales Cloud",
        "Zoho CRM",
        "Microsoft Dynamics 365 Sales",
        "SAP Sales Cloud",
        "Oracle Sales Cloud",
        "SugarCRM",
        "Vtiger CRM",
        "Insightly",
        "Nimble",
        "Copper",
        "Freshsales",
        "Zendesk Sell",
        "Pipedrive",
        "HubSpot CRM",
        "Salesforce Sales Cloud",
        "Zoho CRM",
        "Microsoft Dynamics 365 Sales",
        "SAP Sales Cloud",
        "Oracle Sales Cloud",
        "SugarCRM",
        "Vtiger CRM",
        "Insightly",
        "Nimble",
        "Copper",
        "Freshsales",
        "Zendesk Sell",
        "Pipedrive",
        "HubSpot CRM",
        "Salesforce Sales Cloud",
        "Zoho CRM",
        "Microsoft Dynamics 365 Sales",
        "SAP Sales Cloud",
        "Oracle Sales Cloud",
        
    ],
    "Ressources Humaines": [
      "Recruitment", 
      "Employee Relations", 
      "HR Policies", 
      "Payroll Management", 
      "Training and Development", 
      "Performance Management"
    ],
    Architecture: [
      "AutoCAD", 
      "Revit", 
      "SketchUp", 
      "Building Information Modeling (BIM)", 
      "Architectural Design", 
      "Urban Planning", 
      "Sustainable Design"
    ],
    Design: [
      "Graphic Design", 
      "UI/UX Design", 
      "Adobe Illustrator", 
      "Adobe InDesign", 
      "Visual Communication", 
      "Typography", 
      "Brand Identity"
    ],
    Autre: [
      "Project Management", 
      "Data Analysis", 
      "Research", 
      "Communication", 
      "Problem Solving", 
      "Time Management",
        "Leadership",
        "Teamwork",
        "Creativity",
    ]
  };
  
export default skillsByDomain;
  